stages:
  - setup
  - build
  - test
  - deploy

setup masskit_env:
  stage: setup
  rules:
    - changes:
        - environments/init_masskit.sh
  script:
    - source environments/init_masskit.sh --force --suffix $CI_COMMIT_BRANCH
    - echo "Dumping conda environment..."
    - conda env export --name masskit_${CI_COMMIT_BRANCH} > masskit_conda.yml
  tags:
    - linux
    - masskit
  artifacts:
    paths:
      - masskit_conda.yml

build masskit:
  stage: build
  script:
    - source environments/init_masskit.sh --suffix $CI_COMMIT_BRANCH
    - VERBOSE=1 pip wheel .
  tags:
    - linux
    - masskit
  artifacts:
    paths:
      - masskit*.whl

test masskit:
  stage: test
  dependencies:
    - build masskit
  script:
    - source environments/init_masskit.sh --suffix $CI_COMMIT_BRANCH
    - pip install --force-reinstall masskit*.whl
    - cd tests
    - pytest
    - pip uninstall -y masskit
  tags:
    - linux
    - masskit
  artifacts:
    paths:
      - masskit*.whl
