stages:
  - setup
  - build
  - test
  - deploy

setup:masskit_env:
  stage: setup
  rules:
    - changes:
        - environments/*
  script:
    - source environments/init_masskit.sh --force --suffix $CI_COMMIT_BRANCH
    - echo "Dumping masskit conda environment..."
    - conda env export --name masskit_${CI_COMMIT_BRANCH} > masskit_conda.yml
    - conda deactivate
    - conda deactivate
    - source environments/init_masskit.sh --force --cpu --suffix $CI_COMMIT_BRANCH
    - echo "Dumping masskit_ai_cpu conda environment..."
    - conda env export --name masskit_ai_cpu_${CI_COMMIT_BRANCH} > masskit_ai_cpu_conda.yml
  tags:
    - linux
    - masskit
  artifacts:
    paths:
      - masskit_conda.yml
      - masskit_ai_cpu_conda.yml

build:masskit:
  stage: build
  script:
    - source environments/init_masskit.sh --suffix $CI_COMMIT_BRANCH
    - VERBOSE=1 pip wheel --no-build-isolation .
  tags:
    - linux
    - masskit
  artifacts:
    paths:
      - masskit*.whl

test:masskit:
  stage: test
  needs: ["build:masskit"]
  script:
    - source environments/init_masskit.sh --suffix $CI_COMMIT_BRANCH
    - pip install --force-reinstall masskit*.whl
    - cd tests
    - pytest
    - pip uninstall -y masskit
  tags:
    - linux
    - masskit

deploy:masskit_ai:
  stage: deploy
  trigger: msdc/masskit_ai
