workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - setup
  - build
  - test
  - deploy

setup masskit_env:
  stage: setup
  rules:
    - if: $CI_COMMIT_REF_NAME =~ $CI_DEFAULT_BRANCH
      changes:
        - environments/init_masskit.sh
  script:
    - source environments/init_masskit.sh --force
    - echo "Dumping conda environment..."
    - conda env export --name arrow > masskit_conda.yml
  tags:
    - linux
    - masskit
  artifacts:
    paths:
      - masskit_conda.yml

build masskit:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME =~ $CI_DEFAULT_BRANCH
  script:
    - source environments/init_masskit.sh
    - VERBOSE=1 pip wheel .
  tags:
    - linux
    - masskit
  artifacts:
    paths:
      - masskit*.whl

test masskit:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME =~ $CI_DEFAULT_BRANCH
  dependencies:
    - build masskit
  script:
    - source environments/init_masskit.sh
    - pip install masskit*.whl
    - cd tests
    - pytest
    - pip uninstall masskit
  tags:
    - linux
    - masskit
  artifacts:
    paths:
      - masskit*.whl
