input_source:
  file:
    name: ${oc.env:HOME}/data/nist/ei/2020/replib_2020.parquet
input_update:
  file:
    name: ${oc.env:HOME}/data/nist/ei/2020/mainlib_2020.parquet
output:
  file:
    # output file or output file prefix
    name: ${oc.env:HOME}/data/nist/ei/2020/mainlib_2020.parquet
  
hydra:
  run:
    # working directory
    dir: hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: hydra
  sweep:
    dir: hydra_sweep
  job:
    chdir: False
