input_source:
  file:
    name: ~/data/nist/tandem/SRM1950/SRM1950_lumos.parquet
input_update:
  file:
    name: ~/data/nist/tandem/2020/hr_msms_nist.parquet
output:
  file:
    # output file or output file prefix
    name: ~/data/nist/tandem/2020/hr_msms_nist_fixed_set.parquet
  
hydra:
  run:
    # working directory
    dir: hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: hydra
  sweep:
    dir: hydra_sweep
  job:
    chdir: False
