defaults:
  - conversion/msp: msp_mol
  - conversion/mgf: mgf_peptide
  - conversion/sdf: sdf_nist_mol
  - conversion/parquet: parquet_mol
  - conversion/arrow: arrow_mol
  - conversion/csv: csv_mol
  - override hydra/help: batch_converter_help
  - _self_

input:
  file:
    # list of input file names
    names:
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD10_mp210_structures.SDF
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD20_mp210_structures.SDF
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD25_mp210_structures.SDF
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD30_mp210_structures.SDF
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD50_mp210_structures.SDF
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD10_mp210_structures.SDF
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD20_mp210_structures.SDF
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD25_mp211_structures.SDF
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD30_mp211_structures.SDF
      - ~/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD50_mp211_structures.SDF
  # number of records to generate
  num:

conversion:
  small_molecule:
    # maximum bound of 3D conformer in angstroms (0=no limit)
    max_bound: 0.0
  set:
    # probabilities of dev, train, valid, and test sets as space delimited list
    probabilities: [0.0, 0.99, 0.005, 0.005]
  spectra:
    # min peak intensity allowed in spectral fingerprint
    min_intensity: 0.0
    # the max mz value allowed in spectral fingerprint
    max_mz: 2000
    
output:
  file:
    # output file or output file prefix
    name: ~/data/nist/tandem/SRM1950/SRM1950_lumos.parquet
    # parquet, msp, mzxml
    types:

hydra:
  run:
    # working directory
    dir: hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: hydra
  sweep:
    dir: hydra_sweep
  searchpath:
    - pkg://masskit.conf
  job:
    chdir: False
