input:
  file:
    # list of input file names
    names:
      - ~/data/nist/tandem/2023/sdf/apci_msms_nist.sdf
    # input file type
    type: sdf
    # what is the source of the file? nist or pubchem
    source: nist
  # number of records to generate
  num:

conversion:
  id:
    # name of the id field, like NISTNO. if an integer and reading sdfs, this is the start value of the ids
    field: NISTNO
  small_molecule:
    # maximum bound of 3D conformer in angstroms (0=no limit)
    max_bound: 0.0
  msp:
    # Dict containing instructions on how to parse the value in subfields in msp Comment fields.  For example,
    # "--comment_fields \"{'Filter':(r'@hcd(\d+\.?\d* )', float, 'nce')}\""
    #  where the format is {comment_field_name: (regex, type, field_name)}
    comment_fields:
  set:
    # probabilities of dev, train, valid, and test sets as space delimited list
    probabilities: [0.0, 0.0, 0.0, 1.0]
  spectra:
    # min peak intensity allowed in spectral fingerprint
    min_intensity: 0.0
    # the max mz value allowed in spectral fingerprint
    max_mz: 2000
  csv:
    id:
      field:
      initial_value: 0
    # csv has no column headers in first line
    no_column_headers: False
    # name of the column that will contain rdkit Mol
    mol_column_name: mol
    # name of the column containing SMILES.  null means "SMILES"
    smiles_column_name: null
    delimiter: ","

output:
  file:
    # output file or output file prefix
    name: ~/.masskit_cache/apci_msms_2023.parquet
    # parquet, msp, mzxml
    types: parquet

hydra:
  run:
    # working directory
    dir: hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: hydra
  sweep:
    dir: hydra_sweep
  job:
    chdir: False
