defaults:
  - conversion/msp: msp_mol
  - conversion/mgf: mgf_peptide
  - conversion/sdf: sdf_nist_ri_mol
  - conversion/parquet: parquet_mol
  - conversion/arrow: arrow_mol
  - conversion/csv: csv_mol
  - override hydra/help: batch_converter_help
  - _self_

input:
  file:
    # list of input file names
    names:
      - ~/data/nist/ei/2023/sdf/nist_ri_with_exp_RI.sdf
  # number of records to generate
  num:

conversion:
  small_molecule:
    # maximum bound of 3D conformer in angstroms (0=no limit)
    max_bound: 0.0
  set:
    # probabilities of dev, train, valid, and test sets as space delimited list
    probabilities: [0.0, 0.0, 0.0, 1.0]
  spectra:
    # min peak intensity allowed in spectral fingerprint
    min_intensity: 0.0
    # the max mz value allowed in spectral fingerprint
    max_mz: 2000
    
output:
  file:
    # output file or output file prefix
    name: ~/data/nist/ei/2023/ri_2023.parquet
    # parquet, msp, mzxml
    types: parquet

hydra:
  run:
    # working directory
    dir: hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: hydra
  sweep:
    dir: hydra_sweep
  searchpath:
    - pkg://masskit.conf
  job:
    chdir: False
