# fasta filename
input:
  file:
output:
  file:
protein:
  cleavage:
    # enzyme-style digestion (tryptic, semitryptic, or nonspecific) used to generate peptides.
    digest: tryptic
    # Max missed cleavages
    max_missed: 1
peptide:
  # charge range of peptides
  charge:
    min: 2
    max: 4
  mods:
    # comma separated list of variable modifications to apply to peptides.
    variable: "Phospho{S/T}#Oxidation#Acetyl{^}"
    # comma separated list of fixed modifications to apply to peptides.
    fixed: "Carbamidomethyl"
    # maximum number of variable modifications per peptide
    max: 3
  length:
    min: 7
    max: 30
  # List of NCE values to apply to peptides
  nce:
    - 30
  # If True, do not generate peptides that have more basic residues (RHK) than the precursor charge
  use_basic_limit: True