defaults:
  - override hydra/help: batch_converter_help

input:
  file:
    # list of input file names
    names:
    # input file type
    type:
    # what is the source of the file? nist or pubchem
    source:
    # spectrum type: "mol" or "peptide"
    spectrum_type: mol
  # number of records to generate
  num:

conversion:
  small_molecule:
    # maximum bound of 3D conformer in angstroms (0=no limit)
    max_bound: 0.0
  msp:
    # Dict containing instructions on how to parse the value in subfields in msp Comment fields.  For example,
    # "--comment_fields \"{'Filter':(r'@hcd(\d+\.?\d* )', float, 'nce')}\""
    #  where the format is {comment_field_name: (regex, type, field_name)}
    comment_fields:
    id:
      field:
      initial_value: 0
  sdf:
    id:
      field: NISTNO
      initial_value: 0
  mgf:
    id:
      field:
      initial_value: 0
  arrow:
    id:
      field:
      initial_value: 0
  parquet:
    id:
      field:
      initial_value: 0
  csv:
    id:
      field:
      initial_value: 0
    # csv has no column headers in first line
    no_column_headers: False
    # name of the column that will contain rdkit Mol
    mol_column_name: mol
    # name of the column containing SMILES
    smiles_column_name: SMILES 
    delimiter: ","
  set:
    # probabilities of dev, train, valid, and test sets as space delimited list
    probabilities: [0.0, 1.0, 0.0, 0.0]
  spectra:
    # min peak intensity allowed in spectral fingerprint
    min_intensity: 0.0
    # the max mz value allowed in spectral fingerprint
    max_mz: 2000
  # for batch conversion, the size of the batch
  row_batch_size: 5000
  # whether to annotate the output
  annotate: True
  num_workers: 7  # number of threads for processing

output:
  file:
    # output file or output file prefix
    name:
    # parquet, msp, mzxml
    types:

hydra:
  run:
    # working directory
    dir: hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: hydra
  sweep:
    dir: hydra_sweep
  job:
    chdir: False
