input:
  file:
    # list of input file names
    names:
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD10_mp210_structures.SDF
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD20_mp210_structures.SDF
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD25_mp210_structures.SDF
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD30_mp210_structures.SDF
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_negHCD50_mp210_structures.SDF
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD10_mp210_structures.SDF
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD20_mp210_structures.SDF
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD25_mp211_structures.SDF
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD30_mp211_structures.SDF
      - ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos_posHCD50_mp211_structures.SDF
    # input file type
    type:
    # what is the source of the file? nist or pubchem
    source:
  # number of records to generate
  num:

conversion:
  id:
    # name of the id field, like NISTNO. if an integer and reading sdfs, this is the start value of the ids
    field: 10022000000
  small_molecule:
    # maximum bound of 3D conformer in angstroms (0=no limit)
    max_bound: 0.0
  msp:
    # Dict containing instructions on how to parse the value in subfields in msp Comment fields.  For example,
    # "--comment_fields \"{'Filter':(r'@hcd(\d+\.?\d* )', float, 'nce')}\""
    #  where the format is {comment_field_name: (regex, type, field_name)}
    comment_fields:
  set:
    # probabilities of dev, train, valid, and test sets as space delimited list
    probabilities: [0.0, 0.0, 0.1, 0.9]
  spectra:
    # min peak intensity allowed in spectral fingerprint
    min_intensity: 0.0
    # the max mz value allowed in spectral fingerprint
    max_mz: 2000

output:
  file:
    # output file or output file prefix
    name: ${oc.env:HOME}/data/nist/tandem/SRM1950/SRM1950_lumos.parquet
    # parquet, msp, mzxml
    types:
