input:
  file:
    # list of input file names
    names:
      - ${oc.env:HOME}/data/nist/aiomics/msp/2022-04-18/AItrain_VelosHumanCho_2022418v2.msp
    # input file type
    type:
    # what is the source of the file? nist or pubchem
    source:
  # number of records to generate
  num:

conversion:
  id:
    # name of the id field, like NISTNO. if an integer and reading sdfs, this is the start value of the ids
    field: 10027000000
  small_molecule:
    # maximum bound of 3D conformer in angstroms (0=no limit)
    max_bound: 0.0
  msp:
    # Dict containing instructions on how to parse the value in subfields in msp Comment fields.  For example,
    # "--comment_fields \"{'Filter':(r'@hcd(\d+\.?\d* )', float, 'nce')}\""
    #  where the format is {comment_field_name: (regex, type, field_name)}
    comment_fields:
  set:
    # probabilities of dev, train, valid, and test sets as space delimited list
    probabilities: [0.01, 0.97, 0.01, 0.01]
  spectra:
    # min peak intensity allowed in spectral fingerprint
    min_intensity: 0.0
    # the max mz value allowed in spectral fingerprint
    max_mz: 2000

output:
  file:
    # output file or output file prefix
    name: ${oc.env:HOME}/data/nist/aiomics/AItrain_VelosHumanCho_2022418v2.parquet
    # parquet, msp, mzxml
    types:
