input:
  file:
    # list of input file names
    name: ~/data/nist/ei/2020/gary_test_2020.parquet
  # number of records to generate
  num:

conversion:
  max_path_length: 5

output:
  file:
    # output file or output file prefix
    name: ~/data/nist/ei/2020/gary_test_2020_path.parquet

hydra:
  run:
    # working directory
    dir: hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: hydra
  sweep:
    dir: hydra_sweep
  job:
    chdir: False
