input:
  file:
    # list of input file names
    name: ${oc.env:HOME}/data/nist/ei/2023/ri_2023.parquet
  # number of records to generate
  num:

conversion:
  max_path_length: 5

output:
  file:
    # output file or output file prefix
    name: ${oc.env:HOME}/data/nist/ei/2023/ri_2023_path.parquet

hydra:
  run:
    # working directory
    dir: hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: hydra
  sweep:
    dir: hydra_sweep
  job:
    chdir: True
