defaults:
  - override hydra/hydra_logging: none
   # should hydra configure python logging?
  - override hydra/job_logging: none
  - _self_

input:
  file:
    # list of input file names
    name:
  # number of records to generate
  num:

conversion:
  max_path_length: 5

num_workers: 8 

output:
  file:
    # output file or output file prefix
    name:

hydra:
  run:
    # directory to store log files and yaml config
    # e.g. "." or hydra_output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    dir: .
  # subdir of hydra.run.dir that contains hydra config yaml
  # if set to null, will not create. Otherwise, set to "hydra"
  output_subdir: null
  sweep:
    # directory to store log files and yaml config for multiruns
    dir: hydra_sweep
  searchpath:
    - pkg://masskit.conf
  job:
    # change directory to output_subdir?
    chdir: False
