# fasta filename
filename: test.fasta.bz2
outfile: test.parquet
protein:
  cleavage:
    # enzyme-style digestion (tryptic, semitryptic, or nonspecific) used to generate peptides.
    digest: tryptic
    # Max missed cleavages
    max_missed: 0
peptide:
  # charge range of peptides
  charge:
    min: 2
    max: 4
  mods:
    # comma separated list of variable modifications to apply to peptides.
    variable: "Phospho{S}"
    # comma separated list of fixed modifications to apply to peptides.
    fixed: ""
    # maximum number of variable modifications per peptide
    max: 4
  length:
    min: 7
    max: 30
  # List of NCE values to apply to peptides
  nce:
    - 30
